name: ancientgreek-lib
version: 0.0.1

default-extensions: 
  - DataKinds
  - DeriveFunctor
  - DeriveGeneric
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - LambdaCase
  - OverloadedStrings
  - QuasiQuotes
  - RecordWildCards
  - ScopedTypeVariables
  - StrictData
  - TypeApplications

dependencies:
  - base
  - binary
  - bytestring
  - cereal
  - cereal-text
  - conduit
  - containers
  - directory
  - extra
  - filepath
  - hashable
  - haskell-say
  - interpolatedstring-perl6
  - mtl
  - optparse-applicative
  - safe-decimal
  - text
  - transformers
  - transformers
  - type-natural
  - unordered-containers
  - vector
  - xml-conduit
  - xml-types
  - binary-conduit

ghc-options:
  - -Wall
  - -Werror
  - -Wno-orphans

library:
  source-dirs: 
    - src-lib

executables:
  ag-mkdictionary:
    main: Main.hs
    source-dirs: 
      - src-app-mkdictionary
    dependencies:
      - ancientgreek-lib
  ag-parser:
    main: Main.hs
    source-dirs: 
      - src-app-agparser
    dependencies:
      - ancientgreek-lib
      - binary-conduit

tests:
  ancientgreek-test:
    main: MainTest
    source-dirs: 
      - test
      # - src
    dependencies:
      - hspec
      - ancientgreek-lib
      - quickcheck-instances
